Update patch set 3
Patch Set 3: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
find: `src': No such file or directory
frameworks/opt/telephony/src/java/android/telephony/SmsManager.java:540: cannot find symbol
symbol  : variable FORMAT_UNKNOWN
location: class com.android.internal.telephony.SmsConstants
        String format = com.android.internal.telephony.SmsConstants.FORMAT_UNKNOWN;
                                                                   ^
frameworks/opt/telephony/src/java/com/android/internal/telephony/ImsSMSDispatcher.java:43: cannot find symbol
symbol  : variable FORMAT_UNKNOWN
location: class com.android.internal.telephony.SmsConstants
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 3
Label: Code-Review=0
Label: Verified=-1