Update patch set 2
Patch Set 2: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  frameworks/opt/telephony/src/java/com/android/internal/telephony/gsm/GsmCallTracker.java:291: cannot find symbol
symbol  : variable Log
location: class com.android.internal.telephony.gsm.GsmCallTracker
            Log.w(LOG_TAG, "Call Switch request ignored due to pending response");
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 2
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1