Update patch set 2
Patch Set 2: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
build/core/base_rules.mk:513: dalvik/dx/junit-tests/Android.mk: Module "dx-tests" has useless module tags: tests. It will be installed anyway.
build/core/base_rules.mk:513: libcore/Android.mk: Module "core-tests-hostdex" has useless module tags: tests. It will be installed anyway.
find: `src': No such file or directory
frameworks/opt/telephony/src/java/com/android/internal/telephony/Phone.java:132: cannot find symbol
symbol  : variable NETWORK_MODE_LTE_WCDMA
location: interface com.android.internal.telephony.RILConstants
    int NT_MODE_LTE_WCDMA                = RILConstants.NETWORK_MODE_LTE_WCDMA;
                                                       ^
Note: Some input files use or override a deprecated API.
...

Patchset creates breakage in Google's internal tree.

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Patch-set: 2