Update patch set 2
Patch Set 2: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates merge conflict in AOSP.
  The following snippet of `git apply` output may point you in the right direction:
warning: src/java/com/android/internal/telephony/PhoneBase.java has type 100755, expected 100644
error: patch failed: src/java/com/android/internal/telephony/PhoneBase.java:108
error: src/java/com/android/internal/telephony/PhoneBase.java: patch does not apply
error: patch failed: src/java/com/android/internal/telephony/PhoneProxy.java:45
error: src/java/com/android/internal/telephony/PhoneProxy.java: patch does not apply
warning: src/java/com/android/internal/telephony/RIL.java has type 100755, expected 100644
error: patch failed: src/java/com/android/internal/telephony/cdma/CDMALTEPhone.java:28
error: src/java/com/android/internal/telephony/cdma/CDMALTEPhone.java: patch does not apply
error: patch failed: src/java/com/android/internal/telephony/cdma/CDMAPhone.java:50
...

If you wish to pursue this change, please rebase and upload a new patchset.

Patch-set: 2
Label: Code-Review=0
Label: Verified=-1