Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  packages/apps/Dialer/../InCallUI/src/com/android/incallui/InCallActivity.java:435: cannot find symbol
symbol  : class DisconnectCause
location: class com.android.services.telephony.common.Call
    public void maybeShowErrorDialogOnDisconnect(Call.DisconnectCause cause) {
                                                     ^
packages/apps/Dialer/../InCallUI/src/com/android/incallui/InCallActivity.java:481: cannot find symbol
symbol  : class DisconnectCause
location: class com.android.services.telephony.common.Call
    private int getResIdForDisconnectCause(Call.DisconnectCause cause) {
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1