Update patch set 25
Patch Set 25: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
external/bluetooth/bluedroid/Android.mk:8: NO BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR, using only generic configuration
find: `src': No such file or directory
packages/apps/Mms/src/com/android/mms/transaction/TransactionBundle.java:22: cannot find symbol
symbol  : class IccUtils
location: package com.android.internal.telephony
import com.android.internal.telephony.IccUtils;
                                     ^
packages/apps/Mms/src/com/android/mms/transaction/TransactionBundle.java:153: cannot find symbol
symbol  : variable IccUtils
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 25
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1